package actions;

public enum TypeEvent {
	SHUTDOWN, USECLAWSEND, ROTATEEND, PLAYMUSICEND, GOFORWARDEND, GOBACKWARDEND, WAITEND, INTERRUPTED, STRAIGHTMOVEEND, BUMP, ARCEND, BLACKDETECTED, WHITEDETECTED
}
