package actions;

public enum TypeEvent {
	SHUTDOWN, USECLAWS_END, ROTATE_END, PLAYMUSIC_END, GOFORWARD_END, GOBACKWARD_END, WAIT_END,
	INTERRUPTED, STRAIGHTMOVE_END, BUMP, ARC_END, BLACK_DETECTED, WHITE_DETECTED, CHILDBEHAVIOR_END
}
